### ISSUE TITLE
Crash Report Upload URL

### ISSUE THREAD

**Issue by elmiquito** [BirminghamConservatoire/IntegraLive#1024]
The following line of code in GUI/src/assets/IntegraLiveConfig.xml points to a non-existent URL where Crash Reports should be uploaded.
```
<!-- 		url to which crash logs should be uploaded										-->
<crashreporturl>http://integralive.org/upload_crash_log.php</crashreporturl>
```
The upload_crash_log.php file (if it still exists) must be moved to the Integra Lab server.

**Comment by elmiquito** [comment]
The upload_crash_log.php file has been found and moved to this URL: https://integra.io/upload_crash_log.php.

**Comment by jamiebullock** [comment]
@elmiquito Glad you found the file. It turns out I do also have it!

In case you hadn't already figured this out, this will send crash reports to issues@integralive.org with a "from" address of "integra@shipstern.media72.net". I'm not sure the script would even work without further configuration on the server. See [here](https://www.quackit.com/php/tutorial/php_mail_configuration.cfm) but sendmail would also need to be configured.

For the new GUI, I wouldn't recommend this approach. It would be better to do something like use the Gmail API, or a dedicated crash logging service.

**Comment by elmiquito** [comment]
@jamiebullock many thanks for this! Definitely, we will use a different system for crash report for the new GUI as you suggest.
