### ISSUE TITLE
Linux build system

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#26]
---Migrated from Sifter - Sifter issue 32---
Create a build system for Linux so Integra Live can be distributed to Linux users without the need for them to compile the software

**Comment by mxmilkiib** [comment]
I'm wondering about building IntegraLive on Arch Linux. I've not finished trying yet, but here is me experience so far.

I've build the GUI. Arch has `apache-flex-sdk` and `adobe-air-sdk` in the AUR. Unfortunately the `apache-flex-sdk` is only a partial package, though the only file I had to copy into the /opt directory created by the package was airglobal.swc (from https://github.com/madebysource/flex-sdk). After editing the paths in the app-config.xml, I could `make` and get an `IntegraLive.swf`.

On running `make` in `IntegraLive/macosx`, I get

```
make -C ../../GUI/src app
make[1]: Entering directory '/home/milk/src/IntegraLive/GUI/src'
sed  -e 's|x.x.x.xxxx|1.7.11.3322|g' -e 's|x.x.x|1.7.11|g' IntegraLive-app.xml.in > IntegraLive-app.xml
/opt/apache-flex-sdk/bin/amxmlc -compiler.verbose-stacktraces -load-config app-config.xml IntegraLive.mxml
Loading configuration file /home/milk/src/IntegraLive/GUI/src/app-config.xml
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.

make[1]: *** [Makefile:51: IntegraLive.swf] Error 1
make[1]: Leaving directory '/home/milk/src/IntegraLive/GUI/src'
make: *** [Makefile:72: gui] Error 2
make  34.58s user 1.01s system 196% cpu 18.070 total
```

This is because I'm using Wayland instead of X. I'll try under X later, though there might be an obvious reason why the build will fail later on.

**Comment by jamiebullock** [comment]
Hi @milkmiruku, it’s great you’re interested in getting things running on Linux! For info, there is a new version 2 of the software in progress that replaces Adobe AIR with JUCE. This should make Linux builds much more achievable, so you may want to wait until the first public release of that. Cheers, Jamie

**Comment by mxmilkiib** [comment]
Grand, thanks for the update!

To note though, and you might be fully aware of this already, there is some [controversy](https://www.linuxmusicians.com/viewtopic.php?f=24&t=17814) in the Linux community over JUCE over the pricing, application tracking and user tracking features, leading some to label it [spyware](https://linuxmusicians.com/viewtopic.php?f=50&t=19244&p=99415#p99430). Ask in #lad (Linux Audio Development) on Freenode IRC if you might like to know more.

**Comment by rghvdberg** [comment]
Juce?
no thanks

**Comment by jamiebullock** [comment]
@milkmiruku @rghvdberg For info...

It's correct that when JUCE is used under a Personal or Educational license, information is gathered from the user's computer when the splash screen loads. This is a requirement of the JUCE licensing for closed-source applications and is used by Roli to track usage.

**However, when JUCE is used in an open source application, Roli licenses JUCE under the GNU GPL  and no such analytics are collected**. Since Integra Live is itself open source under a GPL license, it will be using JUCE under the GPL license, and will therefore not be required to pass usage data to Roli.

**Comment by mxmilkiib** [comment]
@rghvdberg I'd humbly suggest that form of comment is more noise than signal.

@jamiebullock Thank you for the reply. I guess my understanding is still somewhat muddy though.

Whilst I'm a proponent of [the GPL end of] FLOSS, the situation does seem to create a moral hazard for developers that make closed-source freeware (or those who wish not to distribute their code from the initial publication of their software) but who don't wish to have any form of user tracking enabled. Is there no question on that point, i.e., it so happens there was no option for JUCE using developers to create non-tracking freeware who had wished to upgrade to the latest JUCE for bug fixes?

The tracking feature is enabled by default for all developers? If so, might there have been any rational made public as to why this was the case, rather than opt-in, or leaving the flag blank so a choice has to be made? I understand the hardline privacy viewpoint, but I also understand that there can be an authentic argument made regarding the benefit of tracking to JUCE (or to a plug-in developer via the extra analytics feature). Partly I'd like to read the most "official" line on the specifics, partly I get confused when (all things being equal, i.e., it's not an underdog situation) people perform actions but don't perform speech that removes ambiguity relating to intent regarding those actions.

I've done [some further research](https://linuxmusicians.com/viewtopic.php?p=99920#p99920), and from my still limited understanding now, the basic tracking information is a hash of system inodes or of MAC (plus reporting IP). I'm not a developer so couldn't quite follow the nature of getDeviceDescription, and I couldn't find a decisive clear English statement on exactly what the reported information is. Have I missed a post anywhere related to this?

Will the newer IntegraLive have tracking (or analytics) enabled by default?

Thank you your your time (and code)!

**Comment by jamiebullock** [comment]
Hi @milkmiruku 

I think it's best to ask for clarifications about the JUCE licensing and analytics on the JUCE forum.

All I can say is that for GPL licensed software, there is no requirement from Roli to provide analytics or tracking data for JUCE. In fact any such requirement would be a breach of the terms of the GPL since it would violate the freedom to change the code (and e.g. remove tracking / analytics), which the GPL grants.

In terms of the question:

> Will the newer IntegraLive have tracking (or analytics) enabled by default?

I'd need to get back to you about this when the software is closer to release as my role is helping maintain the Integra framework, and any tracking would be done via the GUI, which is currently still under development. My guess is that if any usage tracking, analytics or crash reporting is added it would be done on an "opt in" basis.

**Comment by rghvdberg** [comment]
I'm sorry bout my comment about Juce.

**Comment by getdunne** [comment]
This issue has been clarified. See https://forum.juce.com/t/projucer-mark-as-gpl-project/23129/4.

We will be using JUCE under the GPL3, which allows us to modify it in any way, including disabling the tracking.

**Comment by 00sapo** [comment]
Hello, right now Integra Live is running well with wine 4.18 (windows version emulated: windows 7) and without additional tricks. Not tested extensively, though... Maybe wine could be an option that could be officially supported?
